### ISSUE TITLE
I can't figure out how to make a transparent sphere

### ISSUE THREAD

**Issue by rjacuna** [DougHamil/threeagent#12]
var material = new THREE.MeshPhysicalMaterial( {
					color: params.color,
					metalness: 0,
					roughness: 0,
					alphaMap: texture,
					alphaTest: 0.5,
					envMap: hdrCubeRenderTarget.texture,
					envMapIntensity: params.envMapIntensity,
					depthWrite: false,
					transparency: params.transparency, // use material.transparency for glass materials
					opacity: 1,                        // set material.opacity to 1 when material.transparency is non-zero
					transparent: true
				} );
Is what the three.js website says I should do.

However the stacktrace in ChromeDevTools says 
![image](https://user-images.githubusercontent.com/28722524/82707570-308b7d80-9c31-11ea-8d49-4ec2db9542b3.png)

**Comment by darwin** [comment]
From the stack trace it looks like you are creating `MeshPhongMaterial` instead of `MeshPhysicalMaterial`. Just my $.02 from what you posted, I have no experience with threeagent.

**Comment by rjacuna** [comment]
@darwin you're right, but that's not the issue. The stack trace gives me the same error 'transparency is not a property' even if I make,

(new three/MeshPhysicalMaterial (cljs/js {
:color "red"
:transparency 0.5 
:transparent true}))

**Comment by darwin** [comment]
Whatever leads to that call is the issue. Three.js complains that `MeshPhongMaterial` does not have `transparency` property. Which is true.

This could be a bug in threeagent which always uses `MeshPhongMaterial` and ignores your material. Also I don't understand what cljs/js means in your code snippet. And it would be great if you used "insert code" when pasting code snippets to github issues (or learn how to format it via markdow).

**Comment by DougHamil** [comment]
It looks like the more recent version of Three.js added a transparency property to MeshPhysicalMaterial.

threeagent defaults to the MeshPhongMaterial when creating a new mesh, but you can explicitly set the Material instance to use by providing it as the `material` key:

```clojure
[:box {:material (new threejs/MeshPhongMaterial (clj->js {:transparency 0.5, :color "red"}))}]
```

If you are still running into issues with this, would you mind providing the threeagent components where you are referencing the MeshPhysicalMaterial?

**Comment by DougHamil** [comment]
I've added a test that shows an example of this: https://github.com/DougHamil/threeagent/blob/main/src/test/threeagent/component_test.cljs#L16
